### ISSUE TITLE
Triggers support

### ISSUE THREAD

**Issue by cemo** [ariga/terraform-provider-atlas#113]
Hi all, 

We would like to give a try terraform provider with new features such as Triggers. I checked the version of `ariga/atlas `in dependencies and it has a version little bid old.

I assume that the capabilities of the this terraform provider is limited with the atlas package in dependencies of this provider. If my assumption is valid, can you please release regularly with `ariga/atlas`.

**Comment by giautm** [comment]
Hello, I'll make a new release today.

**Comment by giautm** [comment]
Hello, The new release already out!, please upgrade to `v0.7.0` and give a try. Thanks!
