### ISSUE TITLE
Token based flow

### ISSUE THREAD

**Issue by cemo** [ariga/terraform-provider-atlas#117]
Hi I would like to use beta features of Atlas but I do not want to use cloud features. 

I created a bot in our cloud account without any project. I added the token into the our provider as this:
```
provider "atlas" {
  cloud {
    token = 'my-token'
  }
}
```

I have 401 errors in terraform. I guess I need to add some more parameters? Can someone help me please?

**Comment by giautm** [comment]
Hello @cemo, please set the token via `ATLAS_TOKEN` environment variable as [in this example](https://github.com/ariga/terraform-provider-atlas/pull/118/commits/044f5d15bd921f50330288ea226472827cf6dd6f) on your CI. It should fix the login issue.

**Comment by luantranminh** [comment]
Hey @cemo, there's now a fix that allows specifying a token in the provider:

```
provider "atlas" {
  cloud {
    token = 'your-token'
  }
}
```

Let's try that, and let me know if there are any issues. Thank you for reporting it. 🚀
