### ISSUE TITLE
Terraform provider does not honor diff / skip logic in firstRunCheck

### ISSUE THREAD

**Issue by dcaputo-harmoni** [ariga/terraform-provider-atlas#130]
The `firstRunCheck` function in `internal/provider/atlas_schema_resource.go` fails when any `DROP` command is present, however it should honor the diff / skip in the `atlas_schema` resource such as:

```
  diff {
    skip {
      drop_table = true
    }
  }
```

In this case, it should not error out on any table drops being present in the migration plan, as they will be skipped.

This use case pattern is important as it provides a way to only focus on a certain schema (i.e. the schema and tables provided to the `atlas_schema` resource via the `hcl` parameter) and ignore others.  Right now there is no way to do this without specifically connecting to that schema, but that doesn't work when the schema is being created by atlas in terraform, as it errors out on the plan stage.

It works as intended when the `firstRunCheck` function is simply bypassed, as I've done in an alternate version of your provider if you'd like to try it (it's hosted on terraform as `dcaputo-harmoni/atlas` - and the only change is bypassing that function).  But that's obviously not the ideal solution for a number of reasons, it simply gets past the issue.

**Comment by giautm** [comment]
The firstRunCheck is ensure developer didn't accident drop their database. And sorry, we won't change this logic. Thank you,

**Comment by dcaputo-harmoni** [comment]
@giautm another point of reference is that the Atlas kubernetes operator supports disabling the `firstRunCheck`:
```
  # Define policies that control how the operator will apply changes to the target database.
  policy:
    # Define a policy that will stop the reconciliation loop if the operator detects
    # a destructive change such as dropping a column or table.
    lint:
      destructive:
        error: true
```
So if you guys aren't planning to allow the same functionality for the terraform provider, I guess I can just use that.
