### ISSUE TITLE
Bad SHA256 hashes on OpenTofu registry

### ISSUE THREAD

**Issue by NathanBaulch** [ariga/terraform-provider-atlas#131]
I'm switching to OpenTofu in a new project and wanted to install this provider but it looks like all the SHA256 hashes are wrong for version 0.8.1 in the OpenTofu registry.

https://github.com/opentofu/registry/blob/f6dcd564a8a01019441040999f2e27eea8976c49/providers/a/ariga/atlas.json#L10-L46

For example, linux_amd64 should be d0d4ba…150dde but appears as 6b0851…bba1c8. The hash values don't appear to match any other common algorithms either.

Not sure where to go from here?

**Comment by NathanBaulch** [comment]
Per https://github.com/opentofu/registry/issues/639, the OpenTofu folks require approval from the atlas maintainers before they can force a resync. @giautm @datdao

**Comment by giautm** [comment]
We created a new release v0.8.2 with the same commit ID, I hope it helps.

**Comment by NathanBaulch** [comment]
Great, hopefully my other PR #132 can be merged soon 🙏
