### ISSUE TITLE
No binaries on recent releases

### ISSUE THREAD

**Issue by NathanBaulch** [ariga/terraform-provider-atlas#134]
Looking forward to using v0.8.3 (with my #132 fix) in OpenTofu, however the last two releases don't contain any binaries because the [build action](https://github.com/ariga/terraform-provider-atlas/actions/runs/9434869234/job/25987525722) is failing with:

```
⨯ release failed after 1m45s
error=sign: gpg failed: exit status 2: gpg: skipped "8256D0CDD3EBD12E4064F82F45441FCEAAC3770C": Unusable secret key
```

**Comment by giautm** [comment]
Fixed in the release v0.8.4, thank you.
