### ISSUE TITLE
Terraform registry not updated with recent releases

### ISSUE THREAD

**Issue by sergeipri** [ariga/terraform-provider-atlas#136]
Hi,

The [terraform registry](https://registry.terraform.io/providers/ariga/atlas/latest) contains versions only up to v0.8.1 , while the github releases has v0.8.3
Will the registry be updated with recent versions, or should we look for alternative installation methods?

Thanks

**Comment by giautm** [comment]
Hey, we fixed the issue when release [`v0.8.4`](https://registry.terraform.io/providers/ariga/atlas/0.8.4/docs). Thank you for patience.
