### ISSUE TITLE
Provider doesn't work with cockroachdb

### ISSUE THREAD

**Issue by achew22** [ariga/terraform-provider-atlas#16]
When testing this out on my cockroach, I ran into the error:

```
  # module.database.atlas_schema.schema will be created
  + resource "atlas_schema" "schema" {
      + dev_db_url = (sensitive value)
      + hcl        = <<-EOT
            schema "public" {
            }

            <Tables et al elided for simplicity, but printed out here>
        EOT
      + id         = (known after apply)
      + url        = (sensitive value)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.database.atlas_schema.schema: Creating...
╷
│ Error: Drop schema named "crdb_internal": pq: cannot drop schema "crdb_internal"
│
│   with module.database.atlas_schema.schema,
│   on ../../modules/database/database.tf line 1, in resource "atlas_schema" "schema":
│    1: resource "atlas_schema" "schema" {
│
╵
```

This was against a test schema, so there was no risk from attempting to drop the schema crdb_internal, but it does freak me out that there was no diff output from the provider during the planning process.

I guess there are 2 issues in here:

1. Atlas probably shouldn't mess with the `crdb_internal` schema no matter what. Maybe the resource should have a way to specify a set of schemas that it should modify?
2. Is there a step I'm missing to get a printout of the about to be executed SQL? If this had printed out a `DROP SCHEMA crdb_internal;` I would not have told it to run. As it stands it kinds of freaks me out that the diff suggested by this run didn't imply that something so dangerous was happening.

**Comment by a8m** [comment]
Thanks for reporting this @achew22 🙏 

This was actually fixed in [Atlas](https://github.com/ariga/atlas/commit/4cc55247a68080ba99f8c2784687fc60180742c8) and we should update its module. Tagging @hedwigz to address it.

**Comment by achew22** [comment]
Great! Sounds like we're already half-way there! Is there any way to have the provider print out the SQL that it is about to run? That would provide a lot of confidence before execution

**Comment by a8m** [comment]
@rotemtam and I just discussed it. I was surprised to see this as well. I'll make sure we add integration tests (in CI) for all the databases that are mentioned here.

 > Is there any way to have the provider print out the SQL that it is about to run? That would provide a lot of confidence before execution

Atlas does this and I think it's required here as well. However, I'm not sure Terraform exposes such capability. We'll do research on this and I'll update this issue soon. Thanks again for reporting this 🙏

**Comment by giautm** [comment]
Close, due to we already support this feature.
