### ISSUE TITLE
Migration data source fails in v0.9.1

### ISSUE THREAD

**Issue by NathanBaulch** [ariga/terraform-provider-atlas#171]
I just upgraded to v0.9.1 and can no longer deploy my project. I get the following unhelpful error:
```
│ Error: Failed to read migration status
│
│   with module.db.data.atlas_migration.this,
│   on ..\modules\db\atlas.tf line 6, in data "atlas_migration" "this":
│    6: data "atlas_migration" "this" {
```
I'm using OpenTofu on Windows and my atlas.exe version is `v0.28.1-11c4e07-canary`. My Atlas provider is configured as follows:
```hcl
provider "atlas" {
  binary_path = "../../.bin/atlas"
  dev_url     = "docker://postgres/16/dev"
}
data "atlas_migration" "this" {
  dir = "../../database/migrations?format=atlas"
  url = "postgres://${local.pg_user}:${local.pg_pass}@${var.rds_instance_endpoint}/${local.pg_db_name}"
}
```
If I run the atlas command manually using the same values it seems to work fine:
```
> ../../.bin/atlas migration state --dir file://../../database/migrations?format=atlas --url postgres://(redacted)
Migration Status: PENDING
  -- Current Version: 20240903123829
  -- Next Version:    20240916175119
  -- Executed Files:  13
  -- Pending Files:   3
```
I don't see any breaking changes listed in the v0.9.1 release notes and the examples folder wasn't touched, so I'm wondering where I've gone wrong!

**Comment by NathanBaulch** [comment]
There was no error printed, just what I shared above. I'm not sure what happened to the underlying error returned by `c.MigrateStatus` or if there's some other way to get it? 🤷
![image](https://github.com/user-attachments/assets/01e9f60e-ed14-4e2d-b9ea-3ffae92fc31c)

**Comment by giautm** [comment]
@NathanBaulch I'll close this issue, if you found anything related to our provider, please ping us and we're ready to help.
