### ISSUE TITLE
Bug: can't use Terraform variable on dev_db_url property

### ISSUE THREAD

**Issue by noiretr-cg** [ariga/terraform-provider-atlas#41]
Hello, 

I have the following message `Warning: dev_db_url is unset` on terraform plan when i use variable on `dev_db_url` property on `atlas_schema` ressource (variable on url property work fine).

Example :

```hcl
resource "atlas_schema" "nifi" {
  hcl = file("${path.module}/db_atlas_schema.hcl")
  url = local.main_instance_url
  dev_db_url = "postgres://pgadmin:${data.vault_kv_secret_v2.secret_pgadmin_user.data.secret}@${var.instance_address}:5432/atlas?sslmode=disable)"
}

**Comment by rotemtam** [comment]
hey @noiretr-cg 
thanks for reaching out. What version of the provider are you using?

**Comment by giautm** [comment]
Hello @noiretr-cg, I think the warning is falsy. Just ignore it for the next version, thank you. 🙏

**Comment by noiretr-cg** [comment]
Hi, 

`0.31` for the Terraform provider and `0.8.0` for Altas

**Comment by noiretr-cg** [comment]
Ok, thanks for your support :+1:
