### ISSUE TITLE
dev_db_url and variables

### ISSUE THREAD

**Issue by L0rdWyd3r** [ariga/terraform-provider-atlas#46]
Hello,
I get a warning when **_dev_db_url_** uses variables

`dev_db_url = "mysql://root:pass@127.0.0.1:${random_integer.mysql_port.result}/${var.mysql_db_name}"`
but when **_dev_db_url_** is defined as below, the problem does not occur.

`dev_db_url = "mysql://root:pass@localhost:3310/main_db"`

In both cases, however, the TCP connection to the database defined in dev_db_url works correctly, as well as the schema is applied correctly.

My only concern is these warnings, is there a chance to eliminate them in the next release ?

Regards

**Comment by giautm** [comment]
Hello @L0rdWyd3r, thank you for reporting the issue. It's falsy warning and it happens on the first time when the resource is being created. I already fixed it, and it should release in the next few days.

Close as duplicated of https://github.com/ariga/terraform-provider-atlas/issues/41

**Comment by L0rdWyd3r** [comment]
Hello @giautm
Thanks a lot for the information, I will wait for the new version in that case :)

Cheers!
