### ISSUE TITLE
TF Provider not found when running from official tf docker image: hashicorp/terraform:1.5.0

### ISSUE THREAD

**Issue by felix-v-net** [ariga/terraform-provider-atlas#72]
data.atlas_migration.this: Reading...
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Failed to read migration status
│ 
│   with data.atlas_migration.this,
│   on 8_sql_migrations.tf line 5, in data "atlas_migration" "this":
│    5: data "atlas_migration" "this" {
│ 
│ fork/exec
│ /app/dev/.terraform/providers/registry.terraform.io/ariga/atlas/0.5.2/linux_amd64/atlas:
│ no such file or directory
╵

**Comment by giautm** [comment]
Hello @felix-v-net, thank you for your report here. I will checkout the docker image and trying to reproduce locally.

**Comment by giautm** [comment]
Hey, just wanna update you that I found the issue with docker-base TF. It's about musl lib issue on alpine. So we working on the fix right now, and will update you again when we release the fix.

**Comment by felix-v-net** [comment]
Hi @giautm ! Sounds promising, do you have an ETA for that? Just to understand if i should look for a workaround or wait for the solution.

**Comment by giautm** [comment]
Hi @felix-v-net, it won't take more than 1-2 days for the fix. Just need to finish sth first before jumping to it. :)

**Comment by giautm** [comment]
@felix-v-net: Hello, please upgrade to latest version of our TF provider. It included the fix for this issue.

**Comment by felix-v-net** [comment]
Hi @giautm ,

Strange, but i still having the same issue:

Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Failed to read migration status
│ 
│   with data.atlas_migration.this,
│   on 06_sql_migrations.tf line 5, in data "atlas_migration" "this":
│    5: data "atlas_migration" "this" {
│ 
│ fork/exec
│ /app/dev/.terraform/providers/registry.terraform.io/ariga/atlas/0.5.3/linux_amd64/atlas:
│ no such file or directory
╵

If it helps, this is my dockerfile:

FROM hashicorp/terraform:1.5.0

# Update package list and install make
RUN apk update && apk add --no-cache make

ARG VERSION

# Check if the VERSION ARG has been set and fail the build if it hasn't
RUN if [ -z "$VERSION" ]; then \
        echo "VERSION is required. Please set it with --build-arg VERSION=0.0.1.123"; \
        exit 1; \
    fi

WORKDIR /app
COPY infra .

ENV AWS_ACCESS_KEY_ID=
ENV AWS_SECRET_ACCESS_KEY=
ENV AWS_REGION=
ENV BUILD_VERSION=$VERSION

WORKDIR /app/${ENVIRONMENT_NAME}

RUN echo '#!/bin/sh' > entrypoint.sh && echo 'cd ${ENVIRONMENT_NAME}; make $1 -f ../Makefile' >> entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

**Comment by giautm** [comment]
@felix-v-net: the correct version is 0.5.4, please upgrade again.

**Comment by felix-v-net** [comment]
@giautm thanks, works now!
