### ISSUE TITLE
Support "allow-dirty" flag

### ISSUE THREAD

**Issue by JensSkipr** [ariga/terraform-provider-atlas#76]
Thanks for this great tool!

Unfortunately, when trying to combine with e.g. https://registry.terraform.io/providers/cyrilgdn/postgresql/, we receive `Error: sql/migrate: connected database is not clean: found schema "xyz". baseline version or allow-dirty is required`.

There seems to be no way to provide the `allow-dirty` argument in the provider. Could you please consider adding support for it?

**Comment by JensSkipr** [comment]
Thanks for your quick reply!

To give the full context, our Terraform consists of 2 working directories:
1. `infra`: Setup DB instance and add DB users on GCP. The latter happens on GCP instead of directly in Postgres to support https://cloud.google.com/sql/docs/postgres/iam-logins.
2. `db`: Setup schema's and roles with `cyrilgdn/postgresql` inside DB.

Our applications are responsible for handling migrations inside their respective schema's. So, this part is not handled by Terraform.

Recently, we introduced a data logging feature. This feature consists of 1 schema, 1 table and 2 functions. Unfortunately, `cyrilgdn/postgresql` doesn't support creating tables, nor "raw" SQL. So, the easiest solution seemed to find a provider which has migrations support for Terraform, where I found Atlas. I hoped to run the migration after the `2. db` step. Using the provider simplified this by having all config in a single place (Terraform). 

So, without the `allow-dirty` flag, another option I see is to run Atlas separately from Terraform. But doing so I would miss the benefit of the Terraform integration.

Below you can find the resource blocks related to the data logging feature. Just be aware we have other schema's, roles, ... as well in the same DB instance.

```terraform
provider "atlas" {}

provider "postgresql" {
  host      = local.postgres_host
  port      = local.postgres_port
  sslmode   = local.postgres_sslmode
  username  = local.postgres_user
  password  = local.postgres_password
  database  = local.postgres_database
}

resource "postgresql_schema" "logging" {
  name  = "logging"
  owner = "postgres"
}

resource "postgresql_grant" "logging" {
  object_type = "schema"
  database    = local.postgres_database
  schema      = postgresql_schema.logging.name
  role        = "public"
  privileges  = ["USAGE"]
}

locals {
  postgres_creds = coalesce(local.postgres_password, "null_or_empty") == "null_or_empty" ? local.postgres_user : "${local.postgres_user}:${local.postgres_password}"
}

// Inspect the target database and load its state.
// This is used to determine which migrations to run.
data "atlas_migration" "logging" {
  dir = "migrations/logging?format=atlas"
  url = "postgres://${local.postgres_creds}@${local.postgres_host}:${local.postgres_port}/${local.postgres_database}?sslmode=${local.postgres_sslmode}"
}

// Sync the state of the target database with the migrations directory.
resource "atlas_migration" "logging" {
  depends_on = [postgresql_schema.logging] # Ensure logging schema exists
  dir        = "migrations/logging?format=atlas"
  version    = data.atlas_migration.logging.latest # Latest runs all migrations
  url        = data.atlas_migration.logging.url
}
```

Personally, I liked creating the functions more in Atlas than `cyrilgdn/postgresql` as the latter had some missing optional directives. Therefore, I included those as well in Atlas instead of using the [postgresql_function](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_function) resource.

**Comment by giautm** [comment]
Hello, thank you for telling the story here. We are very appreciative of that.

For this case, try the `search_path` parameter in the URL. To see if it helps?

For example:

```
url = "postgres://${local.postgres_creds}@${local.postgres_host}:${local.postgres_port}/${local.postgres_database}?sslmode=${local.postgres_sslmode}&search_path=${postgresql_schema.logging.name}"
```

**Comment by rotemtam** [comment]
@JensSkipr 

Glad this solves the issue. Just to add on why it does for others that may hit it in the future. 

Atlas behaves differently if the URL supplied is "schema bound" or "database bound" (internally called "realm bound").

It is similar to how your database behaves if you connect to a specific schema or not. (requiring you to run `USE xyz` or qualify your statements `CREATE TABLE xyz.users ...`

For postgres this looks like this:
![Screen Shot 2023-07-25 at 17 52 14](https://github.com/ariga/terraform-provider-atlas/assets/1522681/d6451398-38f3-4eb6-afbc-fe7a0ba9dbbd)

If you provide the search_path it connects to a specific schema and if you don't, the context is the entire database. In your case, it found some schema "XYZ" and thought that the database was "dirty" because of this.
