### ISSUE TITLE
DB credentials being printed as plaintext

### ISSUE THREAD

**Issue by rwilliams-exs** [ariga/terraform-provider-atlas#86]
When utilising the provider, the `atlas_schema` resource type's ID is the full DB conn string - including the username and password information.

This ID is printed in full as plaintext during any `plan` or `apply` actions.

This is clearly a security issue when considering using this in order to manage a production database.

Ideally I would prefer to set the URL once on the provider in a secure manner, which looks to be possible on the provider currently via the `cloud` block, but is negated by the `atlas_schema` resource requiring the `url` parameter.

**Comment by giautm** [comment]
Hello, What's the version you are using? Because we already removed the Userinfo from the URL that was used for the ID field. (https://github.com/ariga/terraform-provider-atlas/blob/master/internal/provider/atlas_schema_resource.go#L397-L404)

**Comment by rwilliams-exs** [comment]
@giautm I'm using version 0.5.5

**Comment by rwilliams-exs** [comment]
I wonder if this may be related to the format in which I'm providing the credentials within the URL - I was initially seeing an error when providing it in the standard format of:
`postgres://<user>:<pass>@db.url.com/db_name`

> able to generate migration plan, got error: Error: parse "postgres://<user>:<pass>@url.db.com:5432/db_name": invalid port "<pass>" after host

So I instead supplied them in the format:
`postgres://db.url.com/db_name?username=<user>&password=<pass>`
just in order to get something connected

Perhaps I'm missing something in the formatting of the connstring to get the preferred first approach working?

**Comment by rwilliams-exs** [comment]
> The first error is related to unknown value for planning pharse, so TF use a blank value for it.

I don't think this is the case in my instance unfortunately, as the full string is being printed to the console in the error message - including the value of the password in both the connstring and the section that it is interpreting as the port. Apologies if that wasn't clear from my comment, I was attempting to sanitise the data

**Comment by rwilliams-exs** [comment]
I think I may have found something which may contribute to this issue.

My autogenerated password (generated for me by the AWS RDS module) contains the `?` character 

I suspect that this is conflicting with the logic within `url.Parse` [here](https://github.com/ariga/terraform-provider-atlas/blob/master/internal/provider/atlas_schema_resource.go#L398)

**Comment by rwilliams-exs** [comment]
When testing to remove that character from the password string I am seeing a separate error:

`Unable to generate migration plan, got error: Error: parse "postgresql://<user>:<pass<@db.url.com:5432/db_name": net/url: invalid userinfo`

Which makes sense seeing as in removing that character I am providing an incorrect password.

As an aside, the fact that the full unsanitised connstring is being printed to the console log is still problematic - realistically I would expect this to be being flagged as `sensitive` within the provider so as to avoid it being printed in plaintext

**Comment by giautm** [comment]
Hello @rwilliams-exs. The ID field of the resource can't flagged as `sensitive`, that's restricted by TF. We've been tried, but no luck.

Can you share your TF resources with me? Contact me via Discord at `giautm`.

**Comment by giautm** [comment]
Hello, closing this issue. But feel free to reach me if you still facing this issue. Or need more help
