### ISSUE TITLE
Unexpected "Dir is empty" on atlas_migration

### ISSUE THREAD

**Issue by feigi** [ariga/terraform-provider-atlas#88]
Hi again,

I just updated the Terraform provider from 0.4.7 to 0.5.5 and an issue appeared. The first version this is happening to me with is 0.5.3.

I have my `resource "atlas_migration"`  set up like this:

```terraform
data "atlas_migration" "this" {
  dir              = "${var.migrations_folder}?format=atlas"
  url              = local.url
}

resource "atlas_migration" "this" {
  dir              = "${var.migrations_folder}?format=atlas"
  version      = data.atlas_migration.this.latest # Use latest to run all migrations
  url              = local.url
  dev_url      = local.dev_url
}
```

This worked up to 0.5.2 but with a higher version I'm getting this right after running terraform apply:

```shell
> terraform apply
│ Error: dir is empty
│
│   with module.db_migration.atlas_migration.this,
│   on ../modules/db-migration/migrations.tf line 11, in resource "atlas_migration" "this":
│   11: resource "atlas_migration" "this" {
│
│ dir is required when remote_dir is unset
```

Note, that it is failing at the `resource` module even though it has a dependency on the `data` resource. Looking at the `resource "atlas_migration"` code, I can find some validation which checks for empty string. In the `data "atlas_migration"` code no such validation popped into my eye. The fact that the empty string validation fails is weird, because `var.migrations_folder` has a non-empty default value ("migrations") and also I use string interpolation with some added text here, so it should never be empty.
When I don't use string interpolation, i.e. when I hardcode the path in the code above, it works again. I don't know the Terraform Provider API to be of any help I'm afraid.

**Comment by feigi** [comment]
P.S. I had a mistake in the text. 0.5.2 is the last working version in my setup, not the first one failing.

**Comment by rotemtam** [comment]
Hey @feigi,

Thanks for reaching out. Indeed I'm able to reproduce this and I'm seeing something very odd - I get the error you mentioned _only_ if I use string interpolation in `dir`. This behavior directs me to suspect some region of the code which we will check out. 

I will circle back once we have more information.

**Comment by giautm** [comment]
@feigi, Hi. I release the new version (v0.5.6) included a fix for this issue. Please upgrade and let me known if you still have any issue. Thank you,

**Comment by feigi** [comment]
Hi @giautm,

thanks a lot for the quick fix. I just updated and it's looking good so far.

Have a nice day!
